[[tasks]]
name = "启动游戏"
main = "StartGameTask"
module = "SRACore.tasks.StartGameTask"
component = "StartGameComponent"
component_module = "SRACore.component.start_game"

[[tasks]]
name = "清开拓力"
main = "TrailblazePowerTask"
module = "SRACore.tasks.TrailblazePowerTask"
component = "TrailblazePowerComponent"
component_module = "SRACore.component.trailblaze_power"

[[tasks]]
name = "领取奖励"
main = "ReceiveRewardTask"
module = "SRACore.tasks.ReceiveRewardTask"
component = "ReceiveRewardComponent"
component_module = "SRACore.component.receive_reward"

[[tasks]]
name = "模拟宇宙"
main = "SimulateUniverseTask"
module = "SRACore.tasks.SimulateUniverseTask"
component = "SimulateUniverseComponent"
component_module = "SRACore.component.simulate_universe"

[[tasks]]
name = "任务完成"
main = "MissionAccomplishTask"
module = "SRACore.tasks.MissionAccomplishTask"
component = "MissionAccomplishComponent"
component_module = "SRACore.component.mission_accomplish"