name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "StarRailAssistant_*.zip"
          mirrorchyan_rid: StarRailAssistant

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
