#   <StarRailAssistant:An automated program that helps you complete daily tasks of StarRail.>
#   Copyright © <2024> <Shasnow>

#   This file is part of StarRailAssistant.

#   StarRailAssistant is free software: you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free Software Foundation,
#   either version 3 of the License, or (at your option) any later version.

#   StarRailAssistant is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#   without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#   See the GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License along with StarRailAssistant.
#   If not, see <https://www.gnu.org/licenses/>.

#   yukikage@qq.com

name: Build StarRailAssistant

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

permissions:
  contents: write
  actions: write

jobs:
  pre_check:
    name: Pre Checks
    runs-on: ubuntu-latest
    steps:
      - name: Repo Check
        run: |
          if [[ "$GITHUB_REPOSITORY" != "Shasnow/StarRailAssistant" ]]; then
            echo "When forking this repository to make your own builds, you have to adjust this check."
            exit 1
          fi
          exit 0
  build_StarRailAssistant:
    runs-on: windows-latest
    needs: pre_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Built with package.py
        run: |
          python package.py
      - name: Read version
        id: read_version
        run: |
          $VERSION=(Get-Content -Path "version_info.txt" -TotalCount 1).Trim()
          "version=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Add SRAUpdater
        run: |
          Invoke-WebRequest -Uri https://github.com/Shasnow/SRAUpdater/releases/download/SRAUpdater/SRAUpdater.zip -OutFile SRAUpdater.zip
          Expand-Archive -Path StarRailAssistant_${{ env.version }}.zip -DestinationPath StarRailAssistant
          Expand-Archive -Path SRAUpdater.zip -DestinationPath SRAUpdater
          Remove-Item -Path StarRailAssistant_${{ env.version }}.zip
          Remove-Item -Path SRAUpdater.zip
          Copy-Item -Path SRAUpdater\* -Destination StarRailAssistant -Recurse -Force
          Compress-Archive -Path StarRailAssistant\* -DestinationPath StarRailAssistant_${{ env.version }}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StarRailAssistant_${{ env.version }}
          path: StarRailAssistant_${{ env.version }}.zip
      - name: Upload Version_Info Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version_info
          path: version_info.txt